# Generated by Django 3.2.1 on 2024-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
