# Generated by Django 3.2.1 on 2024-06-15 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_alter_book_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
