# Generated by Django 3.2.1 on 2024-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_book_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='book', to='restaurant_app.Book_Table'),
        ),
    ]
