# Generated by Django 3.2.1 on 2024-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_auto_20240615_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, verbose_name='Enquiry')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='book', to='restaurant_app.Booking'),
        ),
    ]
