# Generated by Django 3.2.1 on 2024-06-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_auto_20240615_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
