# Generated by Django 3.2.1 on 2024-06-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_booking_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
