# Generated by Django 3.2.1 on 2024-06-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_app', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('contact', models.CharField(blank=True, max_length=500)),
                ('selected_choice', models.CharField(blank=True, max_length=500)),
                ('selected_plan_paid', models.BooleanField(default=False)),
                ('bookings', models.ManyToManyField(blank=True, related_name='book', to='restaurant_app.Booking')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
