# Generated by Django 3.2.1 on 2024-06-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.table'),
            preserve_default=False,
        ),
    ]
