# Generated by Django 3.2.1 on 2024-06-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0015_alter_message_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
