# Generated by Django 3.2.1 on 2024-06-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0018_auto_20240619_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
